### ISSUE TITLE
Error encountered when compile

### ISSUE THREAD

**Issue by fatgrass** [vusec/blindside#1]
Compile the source code on ubuntu 16.04 vitural machine:
$ uname -a
Linux test 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ make
...
gcc: error: unrecognized command line option ‘-mindirect-branch=thunk’
...
Need more gcc plugins?

**Comment by mariusmue** [comment]
Which gcc version are you running on? Ubuntu 16.04 is a bit dated and comes with [gcc-5.3.1](https://packages.ubuntu.com/xenial/gcc). The mindirect-branch=thunk option, however, seems to be added in gcc-8 and introduces retpolines as defense against certain spectre attacks ([src](https://www.phoronix.com/scan.php?page=article&item=gcc8-mindirect-thunk&num=1)).

**Comment by egoktas** [comment]
Thank you for bringing this up fargrass. Adding the '-mindirect-branch=thunk' cflags to the kernel module is a leftover and is not necessary. I have removed it with commit a48ed0b0f4a9c5fcd5e208a341f67a28b911fd28.

**Comment by egoktas** [comment]
Leaving the issue open for a while to allow commenting.
